export * from "./app/schema.ts";
export * from "./calendar-entry/schema.ts";
export * from "./classreg/schema.ts";
export * from "./exams/schema.ts";
export * from "./messages/schema.ts";
export * from "./profile/schema.ts";
export * from "./session/schema.ts";
export * from "./shared/schema.ts";
export * from "./timetable/schema.ts";
