export {
  AppDataSchema,
  type AppData,
  AppExamIntegrationsSchema,
  type AppExamIntegrations,
  AppPlatformApplicationMenusSchema,
  type AppPlatformApplicationMenus,
  AppThirdPartyDataSchema,
  type AppThirdPartyData,
  DashboardCardsDetailSchema,
  type DashboardCardsDetail,
  DashboardCardsSchema,
  type DashboardCards,
  DashboardCardsStatusSchema,
  type DashboardCardsStatus,
  HomeSchema,
  type Home,
  MobileDataSchema,
  type MobileData,
  OnboardingSchema,
  type Onboarding,
  OnboardingTypeSchema,
  type OnboardingType,
  StartupActionsSchema,
  type StartupActions,
  TodayMetaSchema,
  type TodayMeta,
} from "./app/schema.ts";
export {
  ClassregAbsencesMetaSchema,
  type ClassregAbsencesMeta,
  ClassregHomeworkDateRangeTypeSchema,
  type ClassregHomeworkDateRangeType,
  ClassregHomeworkListSchema,
  type ClassregHomeworkList,
  ClassregHomeworkMetaSchema,
  type ClassregHomeworkMeta,
  ClassregLessonTopicsMetaSchema,
  type ClassregLessonTopicsMeta,
} from "./classreg/schema.ts";
export {
  ExamDetailSchema,
  type ExamDetail,
  ExamFilterSchema,
  type ExamFilter,
  ExamsForClassSchema,
  type ExamsForClass,
  ExamsSchema,
  type Exams,
  ExamStatisticsSchema,
  type ExamStatistics,
} from "./exams/schema.ts";
export {
  MessageComposeRecipientsSchema,
  type MessageComposeRecipients,
  MessageDetailSchema,
  type MessageDetail,
  MessageDraftsSchema,
  type MessageDrafts,
  MessageRecipientFilterSchema,
  type MessageRecipientFilter,
  MessageRecipientOptionSchema,
  type MessageRecipientOption,
  MessageRecipientQuickfiltersSchema,
  type MessageRecipientQuickfilters,
  MessageRecipientSearchSchema,
  type MessageRecipientSearch,
  MessageReplyFormSchema,
  type MessageReplyForm,
  MessageSentSchema,
  type MessageSent,
  MessagesInboxSchema,
  type MessagesInbox,
  MessagesPermissionsSchema,
  type MessagesPermissions,
  MessagesStatusSchema,
  type MessagesStatus,
} from "./messages/schema.ts";
export {
  UserContactDataSchema,
  type UserContactData,
  UserEmailSchema,
  type UserEmail,
} from "./profile/schema.ts";
export { SessionStatusSchema, type SessionStatus } from "./session/schema.ts";
export {
  SchoolyearSchema,
  type Schoolyear,
  TimeGridSchema,
  type TimeGrid,
} from "./shared/schema.ts";
export {
  TimetableAvailableRoomsSchema,
  type TimetableAvailableRooms,
  TimetableCalendarSchema,
  type TimetableCalendar,
  TimetableEntriesSchema,
  type TimetableEntries,
  TimetableEntriesSettingsSchema,
  type TimetableEntriesSettings,
  TimetableEntriesWeekOverviewSchema,
  type TimetableEntriesWeekOverview,
  TimetableExternalCalendarSchema,
  type TimetableExternalCalendar,
  TimetableFilterSchema,
  type TimetableFilter,
  TimetableGridSchema,
  type TimetableGrid,
  TimetableMenuSchema,
  type TimetableMenu,
  TimetableResourceTypeSchema,
  type TimetableResourceType,
  TimetableSearchSchema,
  type TimetableSearch,
} from "./timetable/schema.ts";
